// Mocks generated by Mockito 5.4.6 from annotations
// in mgs_app2/test/widgets/image_upload_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i6;

import 'package:flutter/material.dart' as _i7;
import 'package:image_cropper/image_cropper.dart' as _i8;
import 'package:image_picker/image_picker.dart' as _i5;
import 'package:mgs_app2/models/image_model.dart' as _i4;
import 'package:mgs_app2/services/picker.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ImagePickerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePickerService extends _i1.Mock
    implements _i2.ImagePickerService {
  MockImagePickerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ImageModel?> storeImage(_i4.ImageModel? image) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeImage,
          [image],
        ),
        returnValue: _i3.Future<_i4.ImageModel?>.value(),
      ) as _i3.Future<_i4.ImageModel?>);

  @override
  _i3.Future<_i5.XFile?> getImageFromUser(
          {_i5.ImageSource? source = _i5.ImageSource.gallery}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImageFromUser,
          [],
          {#source: source},
        ),
        returnValue: _i3.Future<_i5.XFile?>.value(),
      ) as _i3.Future<_i5.XFile?>);

  @override
  _i3.Future<_i5.XFile?> getMediaFromUser() => (super.noSuchMethod(
        Invocation.method(
          #getMediaFromUser,
          [],
        ),
        returnValue: _i3.Future<_i5.XFile?>.value(),
      ) as _i3.Future<_i5.XFile?>);

  @override
  _i3.Future<List<_i5.XFile?>?> getMultipleImagesFromUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMultipleImagesFromUser,
          [],
        ),
        returnValue: _i3.Future<List<_i5.XFile?>?>.value(),
      ) as _i3.Future<List<_i5.XFile?>?>);

  @override
  _i3.Future<_i6.Uint8List?> openImageCropperProfilePicture(
    _i5.XFile? imageFile,
    _i7.BuildContext? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #openImageCropperProfilePicture,
          [
            imageFile,
            context,
          ],
        ),
        returnValue: _i3.Future<_i6.Uint8List?>.value(),
      ) as _i3.Future<_i6.Uint8List?>);

  @override
  _i3.Future<_i6.Uint8List?> openImageCropperEventBanner(
    _i5.XFile? imageFile,
    _i7.BuildContext? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #openImageCropperEventBanner,
          [
            imageFile,
            context,
          ],
        ),
        returnValue: _i3.Future<_i6.Uint8List?>.value(),
      ) as _i3.Future<_i6.Uint8List?>);

  @override
  List<_i8.PlatformUiSettings> getUiSettings(
    _i7.BuildContext? context,
    _i8.CropStyle? style,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUiSettings,
          [
            context,
            style,
          ],
        ),
        returnValue: <_i8.PlatformUiSettings>[],
      ) as List<_i8.PlatformUiSettings>);
}
