// Mocks generated by Mockito 5.4.6 from annotations
// in mgs_app2/test/screens/main_screens/all_events_screen_comprehensive_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mgs_app2/models/event_firestore.dart' as _i3;
import 'package:mgs_app2/models/event_model.dart' as _i5;
import 'package:mgs_app2/services/local/favorite_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCollectionReference_0<T extends Object?> extends _i1.SmartFake
    implements _i2.CollectionReference<T> {
  _FakeCollectionReference_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EventFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventFirestore extends _i1.Mock implements _i3.EventFirestore {
  MockEventFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CollectionReference<Object?> get eventsCR => (super.noSuchMethod(
        Invocation.getter(#eventsCR),
        returnValue: _FakeCollectionReference_0<Object?>(
          this,
          Invocation.getter(#eventsCR),
        ),
      ) as _i2.CollectionReference<Object?>);

  @override
  set eventsCR(_i2.CollectionReference<Object?>? _eventsCR) =>
      super.noSuchMethod(
        Invocation.setter(
          #eventsCR,
          _eventsCR,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<List<_i5.EventModel>> retrieveUserJoinedEvents(
          {bool? onlyFuture = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveUserJoinedEvents,
          [],
          {#onlyFuture: onlyFuture},
        ),
        returnValue: _i4.Future<List<_i5.EventModel>>.value(<_i5.EventModel>[]),
      ) as _i4.Future<List<_i5.EventModel>>);

  @override
  _i4.Future<List<_i5.EventModel>> retrieveEvents() => (super.noSuchMethod(
        Invocation.method(
          #retrieveEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i5.EventModel>>.value(<_i5.EventModel>[]),
      ) as _i4.Future<List<_i5.EventModel>>);

  @override
  _i4.Future<void> deleteEvent(_i5.EventModel? event) => (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [event],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> retrieveParticipantsUid(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveParticipantsUid,
          [eventId],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<List<_i5.EventModel>> retrievePersonalEvents({
    bool? onlyFuture = false,
    bool? justCreatedByMe = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrievePersonalEvents,
          [],
          {
            #onlyFuture: onlyFuture,
            #justCreatedByMe: justCreatedByMe,
          },
        ),
        returnValue: _i4.Future<List<_i5.EventModel>>.value(<_i5.EventModel>[]),
      ) as _i4.Future<List<_i5.EventModel>>);

  @override
  _i4.Future<_i5.EventModel?> getEventById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [id],
        ),
        returnValue: _i4.Future<_i5.EventModel?>.value(),
      ) as _i4.Future<_i5.EventModel?>);

  @override
  _i4.Future<String> addEvent(_i5.EventModel? event) => (super.noSuchMethod(
        Invocation.method(
          #addEvent,
          [event],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #addEvent,
            [event],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> editEvent(
    _i5.EventModel? event,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editEvent,
          [
            event,
            id,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #editEvent,
            [
              event,
              id,
            ],
          ),
        )),
      ) as _i4.Future<String>);
}

/// A class which mocks [FavoritesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesService extends _i1.Mock implements _i7.FavoritesService {
  MockFavoritesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveFavorites(List<String>? favorites) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFavorites,
          [favorites],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<bool> isFavorite(String? id) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> addFavorite(String? id) => (super.noSuchMethod(
        Invocation.method(
          #addFavorite,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFavorite(String? id) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
