// Mocks generated by Mockito 5.4.6 from annotations
// in mgs_app2/test/screens/main_screens/event_screen_comprehensive_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:mgs_app2/models/event_firestore.dart' as _i8;
import 'package:mgs_app2/models/event_model.dart' as _i9;
import 'package:mgs_app2/models/participant_model.dart' as _i5;
import 'package:mgs_app2/models/user_firestore.dart' as _i11;
import 'package:mgs_app2/models/user_model.dart' as _i12;
import 'package:mgs_app2/services/functions/firebase_function_caller.dart'
    as _i6;
import 'package:mgs_app2/services/functions/function_handler.dart' as _i2;
import 'package:mgs_app2/services/functions/function_response.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFunctionHandler_0 extends _i1.SmartFake
    implements _i2.FunctionHandler {
  _FakeFunctionHandler_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFunctionResponse_1 extends _i1.SmartFake
    implements _i3.FunctionResponse {
  _FakeFunctionResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionReference_2<T extends Object?> extends _i1.SmartFake
    implements _i4.CollectionReference<T> {
  _FakeCollectionReference_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeParticipantModel_3 extends _i1.SmartFake
    implements _i5.ParticipantModel {
  _FakeParticipantModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseFunctionCaller].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFunctionCaller extends _i1.Mock
    implements _i6.FirebaseFunctionCaller {
  MockFirebaseFunctionCaller() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FunctionHandler get handler => (super.noSuchMethod(
        Invocation.getter(#handler),
        returnValue: _FakeFunctionHandler_0(
          this,
          Invocation.getter(#handler),
        ),
      ) as _i2.FunctionHandler);

  @override
  _i7.Future<_i3.FunctionResponse> isBossCodeValid(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #isBossCodeValid,
          [code],
        ),
        returnValue:
            _i7.Future<_i3.FunctionResponse>.value(_FakeFunctionResponse_1(
          this,
          Invocation.method(
            #isBossCodeValid,
            [code],
          ),
        )),
      ) as _i7.Future<_i3.FunctionResponse>);

  @override
  _i7.Future<_i3.FunctionResponse> sendReport(
    String? section,
    String? text,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendReport,
          [
            section,
            text,
          ],
        ),
        returnValue:
            _i7.Future<_i3.FunctionResponse>.value(_FakeFunctionResponse_1(
          this,
          Invocation.method(
            #sendReport,
            [
              section,
              text,
            ],
          ),
        )),
      ) as _i7.Future<_i3.FunctionResponse>);

  @override
  _i7.Future<_i3.FunctionResponse> joinEvent(
    String? eventId, {
    String? paymentMethodId = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinEvent,
          [eventId],
          {#paymentMethodId: paymentMethodId},
        ),
        returnValue:
            _i7.Future<_i3.FunctionResponse>.value(_FakeFunctionResponse_1(
          this,
          Invocation.method(
            #joinEvent,
            [eventId],
            {#paymentMethodId: paymentMethodId},
          ),
        )),
      ) as _i7.Future<_i3.FunctionResponse>);

  @override
  _i7.Future<_i3.FunctionResponse> leaveEvent(
    String? eventId, {
    String? paymentMethodId = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveEvent,
          [eventId],
          {#paymentMethodId: paymentMethodId},
        ),
        returnValue:
            _i7.Future<_i3.FunctionResponse>.value(_FakeFunctionResponse_1(
          this,
          Invocation.method(
            #leaveEvent,
            [eventId],
            {#paymentMethodId: paymentMethodId},
          ),
        )),
      ) as _i7.Future<_i3.FunctionResponse>);
}

/// A class which mocks [EventFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventFirestore extends _i1.Mock implements _i8.EventFirestore {
  MockEventFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.CollectionReference<Object?> get eventsCR => (super.noSuchMethod(
        Invocation.getter(#eventsCR),
        returnValue: _FakeCollectionReference_2<Object?>(
          this,
          Invocation.getter(#eventsCR),
        ),
      ) as _i4.CollectionReference<Object?>);

  @override
  set eventsCR(_i4.CollectionReference<Object?>? _eventsCR) =>
      super.noSuchMethod(
        Invocation.setter(
          #eventsCR,
          _eventsCR,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<List<_i9.EventModel>> retrieveUserJoinedEvents(
          {bool? onlyFuture = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveUserJoinedEvents,
          [],
          {#onlyFuture: onlyFuture},
        ),
        returnValue: _i7.Future<List<_i9.EventModel>>.value(<_i9.EventModel>[]),
      ) as _i7.Future<List<_i9.EventModel>>);

  @override
  _i7.Future<List<_i9.EventModel>> retrieveEvents() => (super.noSuchMethod(
        Invocation.method(
          #retrieveEvents,
          [],
        ),
        returnValue: _i7.Future<List<_i9.EventModel>>.value(<_i9.EventModel>[]),
      ) as _i7.Future<List<_i9.EventModel>>);

  @override
  _i7.Future<void> deleteEvent(_i9.EventModel? event) => (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [event],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<String>> retrieveParticipantsUid(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveParticipantsUid,
          [eventId],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<List<_i9.EventModel>> retrievePersonalEvents({
    bool? onlyFuture = false,
    bool? justCreatedByMe = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrievePersonalEvents,
          [],
          {
            #onlyFuture: onlyFuture,
            #justCreatedByMe: justCreatedByMe,
          },
        ),
        returnValue: _i7.Future<List<_i9.EventModel>>.value(<_i9.EventModel>[]),
      ) as _i7.Future<List<_i9.EventModel>>);

  @override
  _i7.Future<_i9.EventModel?> getEventById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [id],
        ),
        returnValue: _i7.Future<_i9.EventModel?>.value(),
      ) as _i7.Future<_i9.EventModel?>);

  @override
  _i7.Future<String> addEvent(_i9.EventModel? event) => (super.noSuchMethod(
        Invocation.method(
          #addEvent,
          [event],
        ),
        returnValue: _i7.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #addEvent,
            [event],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> editEvent(
    _i9.EventModel? event,
    String? id,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editEvent,
          [
            event,
            id,
          ],
        ),
        returnValue: _i7.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #editEvent,
            [
              event,
              id,
            ],
          ),
        )),
      ) as _i7.Future<String>);
}

/// A class which mocks [UserFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserFirestore extends _i1.Mock implements _i11.UserFirestore {
  MockUserFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.ParticipantModel> getParticipant(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getParticipant,
          [uid],
        ),
        returnValue:
            _i7.Future<_i5.ParticipantModel>.value(_FakeParticipantModel_3(
          this,
          Invocation.method(
            #getParticipant,
            [uid],
          ),
        )),
      ) as _i7.Future<_i5.ParticipantModel>);

  @override
  _i7.Future<void> updateUserInfo({
    required String? name,
    required String? surname,
    required DateTime? birth,
    required _i12.UserGender? gender,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserInfo,
          [],
          {
            #name: name,
            #surname: surname,
            #birth: birth,
            #gender: gender,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateUserGroup({
    required String? group,
    required String? ispettoria,
    required String? country,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserGroup,
          [],
          {
            #group: group,
            #ispettoria: ispettoria,
            #country: country,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setBossCode({required String? code}) => (super.noSuchMethod(
        Invocation.method(
          #setBossCode,
          [],
          {#code: code},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> registerUser() => (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<_i12.UserModel?> loadUserModel() => (super.noSuchMethod(
        Invocation.method(
          #loadUserModel,
          [],
        ),
        returnValue: _i7.Future<_i12.UserModel?>.value(),
      ) as _i7.Future<_i12.UserModel?>);
}
