// Mocks generated by Mockito 5.4.6 from annotations
// in mgs_app2/test/screens/registration_screens/boss_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mgs_app2/services/functions/firebase_function_caller.dart'
    as _i4;
import 'package:mgs_app2/services/functions/function_handler.dart' as _i2;
import 'package:mgs_app2/services/functions/function_response.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFunctionHandler_0 extends _i1.SmartFake
    implements _i2.FunctionHandler {
  _FakeFunctionHandler_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFunctionResponse_1 extends _i1.SmartFake
    implements _i3.FunctionResponse {
  _FakeFunctionResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseFunctionCaller].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFunctionCaller extends _i1.Mock
    implements _i4.FirebaseFunctionCaller {
  MockFirebaseFunctionCaller() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FunctionHandler get handler => (super.noSuchMethod(
        Invocation.getter(#handler),
        returnValue: _FakeFunctionHandler_0(
          this,
          Invocation.getter(#handler),
        ),
      ) as _i2.FunctionHandler);

  @override
  _i5.Future<_i3.FunctionResponse> isBossCodeValid(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #isBossCodeValid,
          [code],
        ),
        returnValue:
            _i5.Future<_i3.FunctionResponse>.value(_FakeFunctionResponse_1(
          this,
          Invocation.method(
            #isBossCodeValid,
            [code],
          ),
        )),
      ) as _i5.Future<_i3.FunctionResponse>);

  @override
  _i5.Future<_i3.FunctionResponse> sendReport(
    String? section,
    String? text,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendReport,
          [
            section,
            text,
          ],
        ),
        returnValue:
            _i5.Future<_i3.FunctionResponse>.value(_FakeFunctionResponse_1(
          this,
          Invocation.method(
            #sendReport,
            [
              section,
              text,
            ],
          ),
        )),
      ) as _i5.Future<_i3.FunctionResponse>);

  @override
  _i5.Future<_i3.FunctionResponse> joinEvent(
    String? eventId, {
    String? paymentMethodId = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinEvent,
          [eventId],
          {#paymentMethodId: paymentMethodId},
        ),
        returnValue:
            _i5.Future<_i3.FunctionResponse>.value(_FakeFunctionResponse_1(
          this,
          Invocation.method(
            #joinEvent,
            [eventId],
            {#paymentMethodId: paymentMethodId},
          ),
        )),
      ) as _i5.Future<_i3.FunctionResponse>);

  @override
  _i5.Future<_i3.FunctionResponse> leaveEvent(
    String? eventId, {
    String? paymentMethodId = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveEvent,
          [eventId],
          {#paymentMethodId: paymentMethodId},
        ),
        returnValue:
            _i5.Future<_i3.FunctionResponse>.value(_FakeFunctionResponse_1(
          this,
          Invocation.method(
            #leaveEvent,
            [eventId],
            {#paymentMethodId: paymentMethodId},
          ),
        )),
      ) as _i5.Future<_i3.FunctionResponse>);
}
