// Mocks generated by Mockito 5.4.6 from annotations
// in mgs_app2/test/screens/personal_screen/user_boss_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mgs_app2/models/participant_model.dart' as _i2;
import 'package:mgs_app2/models/user_firestore.dart' as _i5;
import 'package:mgs_app2/models/user_model.dart' as _i7;
import 'package:mgs_app2/services/functions/firebase_function_caller.dart'
    as _i8;
import 'package:mgs_app2/services/functions/function_handler.dart' as _i3;
import 'package:mgs_app2/services/functions/function_response.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeParticipantModel_0 extends _i1.SmartFake
    implements _i2.ParticipantModel {
  _FakeParticipantModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFunctionHandler_1 extends _i1.SmartFake
    implements _i3.FunctionHandler {
  _FakeFunctionHandler_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFunctionResponse_2 extends _i1.SmartFake
    implements _i4.FunctionResponse {
  _FakeFunctionResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserFirestore extends _i1.Mock implements _i5.UserFirestore {
  MockUserFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ParticipantModel> getParticipant(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getParticipant,
          [uid],
        ),
        returnValue:
            _i6.Future<_i2.ParticipantModel>.value(_FakeParticipantModel_0(
          this,
          Invocation.method(
            #getParticipant,
            [uid],
          ),
        )),
      ) as _i6.Future<_i2.ParticipantModel>);

  @override
  _i6.Future<void> updateUserInfo({
    required String? name,
    required String? surname,
    required DateTime? birth,
    required _i7.UserGender? gender,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserInfo,
          [],
          {
            #name: name,
            #surname: surname,
            #birth: birth,
            #gender: gender,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateUserGroup({
    required String? group,
    required String? ispettoria,
    required String? country,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserGroup,
          [],
          {
            #group: group,
            #ispettoria: ispettoria,
            #country: country,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setBossCode({required String? code}) => (super.noSuchMethod(
        Invocation.method(
          #setBossCode,
          [],
          {#code: code},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> registerUser() => (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i7.UserModel?> loadUserModel() => (super.noSuchMethod(
        Invocation.method(
          #loadUserModel,
          [],
        ),
        returnValue: _i6.Future<_i7.UserModel?>.value(),
      ) as _i6.Future<_i7.UserModel?>);
}

/// A class which mocks [FirebaseFunctionCaller].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFunctionCaller extends _i1.Mock
    implements _i8.FirebaseFunctionCaller {
  MockFirebaseFunctionCaller() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FunctionHandler get handler => (super.noSuchMethod(
        Invocation.getter(#handler),
        returnValue: _FakeFunctionHandler_1(
          this,
          Invocation.getter(#handler),
        ),
      ) as _i3.FunctionHandler);

  @override
  _i6.Future<_i4.FunctionResponse> isBossCodeValid(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #isBossCodeValid,
          [code],
        ),
        returnValue:
            _i6.Future<_i4.FunctionResponse>.value(_FakeFunctionResponse_2(
          this,
          Invocation.method(
            #isBossCodeValid,
            [code],
          ),
        )),
      ) as _i6.Future<_i4.FunctionResponse>);

  @override
  _i6.Future<_i4.FunctionResponse> sendReport(
    String? section,
    String? text,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendReport,
          [
            section,
            text,
          ],
        ),
        returnValue:
            _i6.Future<_i4.FunctionResponse>.value(_FakeFunctionResponse_2(
          this,
          Invocation.method(
            #sendReport,
            [
              section,
              text,
            ],
          ),
        )),
      ) as _i6.Future<_i4.FunctionResponse>);

  @override
  _i6.Future<_i4.FunctionResponse> joinEvent(
    String? eventId, {
    String? paymentMethodId = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #joinEvent,
          [eventId],
          {#paymentMethodId: paymentMethodId},
        ),
        returnValue:
            _i6.Future<_i4.FunctionResponse>.value(_FakeFunctionResponse_2(
          this,
          Invocation.method(
            #joinEvent,
            [eventId],
            {#paymentMethodId: paymentMethodId},
          ),
        )),
      ) as _i6.Future<_i4.FunctionResponse>);

  @override
  _i6.Future<_i4.FunctionResponse> leaveEvent(
    String? eventId, {
    String? paymentMethodId = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #leaveEvent,
          [eventId],
          {#paymentMethodId: paymentMethodId},
        ),
        returnValue:
            _i6.Future<_i4.FunctionResponse>.value(_FakeFunctionResponse_2(
          this,
          Invocation.method(
            #leaveEvent,
            [eventId],
            {#paymentMethodId: paymentMethodId},
          ),
        )),
      ) as _i6.Future<_i4.FunctionResponse>);
}
