// Mocks generated by Mockito 5.4.6 from annotations
// in mgs_app2/test/screens/personal_screen/user_info_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mgs_app2/models/participant_model.dart' as _i2;
import 'package:mgs_app2/models/user_firestore.dart' as _i3;
import 'package:mgs_app2/models/user_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeParticipantModel_0 extends _i1.SmartFake
    implements _i2.ParticipantModel {
  _FakeParticipantModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserFirestore extends _i1.Mock implements _i3.UserFirestore {
  MockUserFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ParticipantModel> getParticipant(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getParticipant,
          [uid],
        ),
        returnValue:
            _i4.Future<_i2.ParticipantModel>.value(_FakeParticipantModel_0(
          this,
          Invocation.method(
            #getParticipant,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.ParticipantModel>);

  @override
  _i4.Future<void> updateUserInfo({
    required String? name,
    required String? surname,
    required DateTime? birth,
    required _i5.UserGender? gender,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserInfo,
          [],
          {
            #name: name,
            #surname: surname,
            #birth: birth,
            #gender: gender,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateUserGroup({
    required String? group,
    required String? ispettoria,
    required String? country,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserGroup,
          [],
          {
            #group: group,
            #ispettoria: ispettoria,
            #country: country,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setBossCode({required String? code}) => (super.noSuchMethod(
        Invocation.method(
          #setBossCode,
          [],
          {#code: code},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> registerUser() => (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i5.UserModel?> loadUserModel() => (super.noSuchMethod(
        Invocation.method(
          #loadUserModel,
          [],
        ),
        returnValue: _i4.Future<_i5.UserModel?>.value(),
      ) as _i4.Future<_i5.UserModel?>);
}
